version: '3.8'
services:
  reporting:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ../data:/data
    container_name: evidently_dashboard
