services:
  reporting:
    container_name: reporting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Map port 8082 on the container to your host machine
    volumes:
      - ../data:/data  # Mount the data directory to the container
