version: '3.8'
services:
  reporting:
    build: .
    container_name: evidently_reporting
    ports:
      - "8082:8082"
    volumes:
      - ../data:/data
      - ./reporting/evidently_ui_workspace:/app/reporting/evidently_ui_workspace
