version: '3.8'

services:
  serving-api:
    container_name: serving-api
    build:
      context: . #sur le meme dossier on trouve le Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose le port 8080 de l'API
    volumes:
      - ../data:/data # Partage le dossier data avec le conteneur
      - ../artifacts:/artifacts  # Partage le dossier artifacts avec le conteneur
      - .:/app  # Monte le dossier courant dans /app
    networks:
      - prod_net # Connecte ce service au réseau prod_net

# Définition du réseau
networks:
  prod_net:
    driver: bridge